const ADD_FAVORITE = "ADD_FAVORITE";
const REMOVE_FAVORITE = "REMOVE_FAVORITE";
const LOG_IN = "LOG_IN";
const SIGN_UP = "SIGN_UP";
const SET_TOKEN = "SET_TOKEN";
const SET_TODOS = "SET_TODOS";
const ADD_TODOS = "ADD_TODOS";
const DELETE_TODOS = "DELETE_TODOS";
const EDIT_TODOS = "EDIT_TODOS";
const COLORS = {
  MAIN_RED: "#DB4C3F",
  MAIN_BLACK: "#262C35",
  BG_GREY: "#EEEEEE",
  BG_BLUE: "#3025B9",
  CARD_URGENT: "#FF2831",
  CARD_HIGH: "#E38901",
  CARD_MEDIUM: "#3483E1",
  CARD_LOW: "#8C8C8C",
  CARD_CATEGORY: "#545454",
  CARD_TIME: "#6EBE6D",
  COMPLETED: "#08A835",
  BG_COMPLETED: "#DBEDDE",
  INPROGRESS: "#00ACD7",
  BORDER_GRAY: "#B8B8B8",
  LIGHT_GRAY: "#CDCDCD",
};

export {
  ADD_FAVORITE,
  REMOVE_FAVORITE,
  SET_TOKEN,
  COLORS,
  SET_TODOS,
  ADD_TODOS,
  DELETE_TODOS,
  EDIT_TODOS,
  LOG_IN,
  SIGN_UP,
};
