name: Azure ACR BE

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t thaitodoacrbe.azurecr.io/thaitodobe
          docker push thaitodoacrbe.azurecr.io/thaitodobe

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy_job
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "todowebappduong"
          slot-name: "production"
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: "thaitodoacrbe.azurecr.io/thaitodobe"
