name: Azure ACR BE

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t thaitodoacrbe.azurecr.io/thaitodobe
          docker push thaitodoacrbe.azurecr.io/thaitodobe

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy_job
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "todowebappduong"
          slot-name: "production"
          publish-profile: <publishData><publishProfile profileName="ca-sea-webapp-thai-backend - Web Deploy" publishMethod="MSDeploy" publishUrl="ca-sea-webapp-thai-backend.scm.azurewebsites.net:443" msdeploySite="ca-sea-webapp-thai-backend" userName="$ca-sea-webapp-thai-backend" userPWD="TF5ZjZQPoqXZifasolDPSYSsyv5mniYK3CaxWNop3H2dgcKkZsoCNWQiejyP" destinationAppUrl="http://ca-sea-webapp-thai-backend.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="ca-sea-webapp-thai-backend - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-197.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="ca-sea-webapp-thai-backend\$ca-sea-webapp-thai-backend" userPWD="TF5ZjZQPoqXZifasolDPSYSsyv5mniYK3CaxWNop3H2dgcKkZsoCNWQiejyP" destinationAppUrl="http://ca-sea-webapp-thai-backend.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="ca-sea-webapp-thai-backend - Zip Deploy" publishMethod="ZipDeploy" publishUrl="ca-sea-webapp-thai-backend.scm.azurewebsites.net:443" userName="$ca-sea-webapp-thai-backend" userPWD="TF5ZjZQPoqXZifasolDPSYSsyv5mniYK3CaxWNop3H2dgcKkZsoCNWQiejyP" destinationAppUrl="http://ca-sea-webapp-thai-backend.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          images: "thaitodoacrbe.azurecr.io/thaitodobe"
